Er us 32
WillWeston94/little-shop-7 pull request #35
Opened 2023-09-14 21:28 UTC by TheAveryRodriguez

MERGE USER STORY 6 FIRST

Database/Migrations:
N/A

Routes:
Added /admin/invoices and /admin/invoices/:id 

Models:
N/A

Controllers:
Created the Admin::InvoicesController

Views:
Created the /admin/invoices views: index and show pages

Testing:
Models:
N/A

Features:
Created and tested the /admin/invoices index and show tests

Considerations(Extra notes, refactors, etc.):
This will complete US 32 + 33. I am currently in the middle of US 34 but believe Nick is working on stuff that can benefit from what we worked on together so I am PR'ing this a little prematurely. ROUTES got changed to have "" instead of single quotes ''. Its a formatting  thing that I did accidentally. It should impact anything but worth mentioning. Besides those things, I think one spec file got a little cleaned up (just removed un-necessary spaces/line breaks). Everything should be pretty good to go.

2023-09-14 23:09 UTC, NSMcEnroe commented on app/views/admin/invoices/index.html.erb
Nice thinking with the .any?

2023-09-14 23:18 UTC, NSMcEnroe approved these changes
Everything looks good on my end, and I just fixed the merge confict.  However, it would be great if someone else got their eyes on it, since Ed and I paired programmed a little bit earlier to do some debugging.  

Just a heads up as well, Ed and I realized we aren't quite done with US 33.  The tests pass, but status is not rendering properly for the invoice show page.  I'll take a glance at that later, but if any one else wants to take a peek at it, be my guest.

2023-09-15 02:25 UTC, WillWeston94 commented
In admin invoices index spec 

      invoice1 = customer.invoices.create!(status: 0)
      invoice2 = customer.invoices.create!(status: 1)
      invoice3 = customer.invoices.create!(status: 2)
      
      standard format should be 
      
      invoice_1 = customer.invoices.create!(status: 0)
      invoice_2 = customer.invoices.create!(status: 1)
      invoice_3 = customer.invoices.create!(status: 2)

2023-09-15 02:26 UTC, WillWeston94 commented
Same with the show spec 

the items and invoices should be snakecase in the spec instance creations

2023-09-15 02:31 UTC, WillWeston94 commented on spec/features/admin/invoices/index_spec.rb
customer = Customer.create!(
        first_name: "Satoshi",
        last_name: "Nakamoto"
      )
      
      A note to make sure we are being consistent across the board on our testing with Factory_Bot instead of CustomerCreate!

2023-09-15 02:33 UTC, WillWeston94 commented on spec/features/admin/invoices/show_spec.rb
Snakecase everything like mentioned before

2023-09-15 02:35 UTC, WillWeston94 requested changes
See comments for changes before merge

2023-09-15 17:34 UTC, WillWeston94 commented
Changes complete! Thank you!

2023-09-15 17:34 UTC, merged